### ISSUE TITLE
[DB] DB 실행환경 결정

### ISSUE THREAD

**Issue by kevin0309** [kevin0309/Cowork_Project_2021#10]
- AWS 인스턴스 내에서 MySQL 설치
- AWS RDS 사용
- 이미 설치된 MySQL사용

**Comment by suehyun** [comment]
### DB 실행환경 결정
내용
* 기존 unbuntu에서 mysql을 설치하여 데이터베이스를 생성하고 접근했을 때 오류가 발생함.
* RDS의 경우 데이터베이스 생성과 접근이 빠르고 쉬움.

결론
* AWS에서 제공하는 서비스인 RDS 선택

> DB 인스턴스 ID: cowork-rds
> 엔드포인트: cowork-rds.c9acto1zciwv.ap-northeast-2.rds.amazonaws.com
> 사용자이름: root
