### ISSUE TITLE
[DB] DB 설계 초안 작성

### ISSUE THREAD

**Issue by kevin0309** [kevin0309/Cowork_Project_2021#11]
- ERD 작성
- 엑셀로 정리

**Comment by suehyun** [comment]
[book_DB.xlsx](https://github.com/kevin0309/Cowork_Project_2021/files/5792617/book_DB.xlsx)

### 데이터베이스 설계 
* 사용자(user_info)
* 책 정보(book_info)
* 책 카테고리(book_category) 
* 책 태그(book_tags)
* 판매 기록(book_sales_info)

**Comment by kevin0309** [comment]
![cowork_tables](https://user-images.githubusercontent.com/32089450/104124666-62567d80-5395-11eb-9079-e21679be0389.JPG)

### 설계를 토대로 ERD 작성
