### ISSUE TITLE
[Crawling] 크롤링 모듈 타겟 설정

### ISSUE THREAD

**Issue by suehyun** [kevin0309/Cowork_Project_2021#14]
타겟 조사
* 후보군: 온라인 서점 홈페이지 
ex) 교보문고, 예스24, 알라딘, 인터파크, 영풍문고, 서울문고

타겟 데이터 조사
* ex) 책 정보, 웹 페이지 동작 방식(동적/정적)

**Comment by kevin0309** [comment]
### yes24
1. 카테고리별 목록
	- http://www.yes24.com/24/Category/Display/001001001006
	- 이런식으로 끝에 카테고리 depth별 url을 생성하여 접근
	- 카테고리 path를 3글자씩 나눠보면 category별 분류체계를 알 수 있음

2. 목록에서 책 id 찾기
	- /html/body/div/div[3]/div[2]/div[4]/ul/li[1]/div/input
	- 해당 hidden input 태그 내의 value.goods_no 에 해당 책의 id가 나와있음

3. 책 상세페이지 접근
	- http://www.yes24.com/Product/Goods/3774048
	- 이런식으로 찾아낸 책 id를 사용하여 책 상세페이지 접근 가능

4. 상세페이지에서 값 추출
	- 제목: #yDetailTopWrap > div.topColRgt > div.gd_infoTop > div > h2
	- isbn10: #infoset_specific > div.infoSetCont_wrap > div > table > tbody > tr:nth-child(4) > td
	- isbn13: #infoset_specific > div.infoSetCont_wrap > div > table > tbody > tr:nth-child(3) > td
	- 저자: #yDetailTopWrap > div.topColRgt > div.gd_infoTop > span.gd_pubArea > span.gd_auth > a
	- 출판사: #yDetailTopWrap > div.topColRgt > div.gd_infoTop > span.gd_pubArea > span.gd_pub > a
	- 출판일자: #infoset_specific > div.infoSetCont_wrap > div > table > tbody > tr:nth-child(1) > td
	- 카테고리: 
	- 판매가: #yDetailTopWrap > div.topColRgt > div.gd_infoBot > div.gd_infoTbArea > div:nth-child(3) > table > tbody > tr:nth-child(1) > td > span > em
	- 쪽수: #infoset_specific > div.infoSetCont_wrap > div > table > tbody > tr:nth-child(2) > td
	- 도서판매지수: #yDetailTopWrap > div.topColRgt > div.gd_infoTop > span.gd_ratingArea > span.gd_sellNum

### 인터파크도서 (전체적으로 table을 사용하여 화면배치되어있음 극혐;;)
1. 카테고리 분류
	- 카테고리 분류가 난해함 yes24와 같이 3자리씩 끊어서 비슷하게 분류되어있는것같으나 숫자가 순차적으로 증가하지 않는것처럼 보임(섞여있을 수도 있음)
	- ==> 목록을 직접 선택하여 순회해야 할것 같음

2. 목록 접근
	- 국내도서와 그 외 도서들의 url패턴이 다른것을 확인
	- 목록: #cnb_con_1 > table
	- 목록에서 각각의 카테고리로 직접 접근할 필요 있음

3. 책 상세페이지 접근
	- 목록에서 #DW_ContentsWrap4 > form > table.list_view01 > tbody > tr:nth-child(5) > td:nth-child(5) > dl > dt:nth-child(2) > strong > a 에 접근하여 url을 알아낼 수 있음
	- http://book.interpark.com/product/BookDisplay.do?_method=Detail&sc.prdNo=338945136 파라미터는 이 두가지만 넘겨줘도 작동함
	
4. 상세페이지에서 값 추출
	- 제목: #inc_titWrap > div.prod_title > div > h2
	- isbn10: 
	- isbn13: #inc_optionWrap > div.optionRight_wrap > div.bookInfoBox > ul > li:nth-child(6)
	- 저자: #inc_optionWrap > div.optionRight_wrap > div.bookInfoBox > ul > li:nth-child(1) > a
	- 출판사: #hdelvMafcEntrNm
	- 카테고리: #inc_optionWrap > div.optionRight_wrap > div.bookInfoBox > ul > li:nth-child(3)
	- 판매가: #inc_optionWrap > div.optionRight_wrap > div.basicInfoBox > table > tbody > tr > td > p
	- 쪽수: #inc_optionWrap > div.optionRight_wrap > div.bookInfoBox > ul > li:nth-child(4)
	- 도서판매지수: #inc_optionWrap > div.optionLeft_wrap > div.saleIndexWrap > div > span

**Comment by suehyun** [comment]
### 타겟 조사
* 교보문고, 알라딘, 영풍문고

### 타겟 데이터 조사
* [조사 내용](https://drive.google.com/file/d/1PQVKmz6KLIJ38JPGN8FTn4z1G6WW3DrD/view?usp=sharing)
