### ISSUE TITLE
[Crawling] 크롤링 모듈 API(BeautifulSoup,Selenium) 사용

### ISSUE THREAD

**Issue by suehyun** [kevin0309/Cowork_Project_2021#15]
크롤링 모듈 API 사용하여 실제 타겟에 적용해보기
* 크롤링 모듈 API: BeautifulSoup,Selenium
* 타겟: 교보문고, 예스24, 알라딘, 인터파크, 영풍문고, 서울문고

**Comment by kevin0309** [comment]
### 영풍문고 책 정보 크롤링 할 페이지 요청방법 분석
- 사용 예시: http://www.ypbooks.co.kr/search.yp?catesearch=true&collection=books_kor&sortField=DATE&c3=100101&startCnt=0&showCnt=1000  
카테고리가 100101 (국어사전)인 리스트에서 0 ~ 1000번째 도서 가져오기  
![캡처](https://user-images.githubusercontent.com/32089450/104251762-c53e3680-54b3-11eb-8576-fb837234087e.JPG)
- URL: http://www.ypbooks.co.kr/search.yp
- method: GET, POST (둘 다 똑같이 동작함)
- param (필수값)
    키|밸류|비고
    ---|---|---
    collection|books_kor|국내 도서라는 의미인것 같음
    catesearch|true|
    sortField|DATE|정렬 방식 (RANK, DATE, SALE_TOTAL_CNT, REVIEWCNT, PRICE, CLICKCNT)
    c3|{yp_cat3 code}|Cowork DB에 book_category 테이블 참고
    startCnt|{0 이상의 값}|검색 결과목록 시작 카운트 (시작 cnt값은 0)
    showCnt|{1 ~ 1000 사이의 값}|검색 결과목록 한 페이지에 나타낼 도서 수 (1000보다 큰 수를 넣으면 결색결과 나오지 않음)
- param (선택)
    키|밸류|비고
    ---|---|---
    searchfield|NULL|
    requery|NULL|
    detailchk|N|
    notSoldOut|N|품절된 품목을 제외하는 값인줄 알았으나 Y를 넣어도 동작하지 않음
    s_rate|NULL|
    e_rate|NULL|
    s_sale_rate|NULL|
    e_sale_rate|NULL|
    viewStyle|list|
    slidevalue1|0|
    slidevalue2|0|
    slidevalue3|0|
    idx|NULL|
    d_title|NULL|
    d_author|NULL|
    d_consume|NULL|
    d_body|NULL|
    d_isbn|NULL|
    gubun|ALL|
    s_pubdt|NULL|
    e_pubdt|NULL|
    s_price|NULL|
    e_price|NULL|
    soldout|N|품절된 품목에 관련된 값 같으나 Y를 넣어도 달라지는게 없음
    select3|DATE|
    query|{검색어}|책제목, 저자, 출판사 세가지 범위 내에서 검색됨
- param (사용X)
    키|밸류|비고
    ---|---|---
    c1|{yp_cat1 code}|c3와 동시에 사용할 수 없음
    c2|{yp_cat2 code}|c3와 동시에 사용할 수 없음
