### ISSUE TITLE
[Crawling] 크롤링 한 데이터를 DB에 등록하는 코드 구현

### ISSUE THREAD

**Issue by suehyun** [kevin0309/Cowork_Project_2021#23]
* [영풍문고 웹 사이트](http://www.ypbooks.co.kr/kor_index.yp)에서 크롤링 한 데이터를 데이터베이스에 등록하는 코드 Python으로 구현 하기

**Comment by kevin0309** [comment]
### TODO
crawling_module.py 책 목록 삽입 시 이전에 등록되어있던 책은 스킵하도록 최적화하는 코드 추가할것!
1. 크롤링단계부터 최신 등록된 책정보 선별 (가능하면!)
3. DB에 이미 저장된 책인지 알아보기
2. 크롤링한 책 목록과 DB에 저장된 목록 비교하기
3. 실행 스케줄링

**Comment by suehyun** [comment]
### 크롤링 단계에서 최신 등록된 책정보 선별
  * 크롤링 할 데이터를 필터링 할 수 있도록 함수에 기준 일의 시작(fixed_pub_date_start)과 끝(fixed_pub_date_end)을 인자로 추가
  * 주기적으로 크롤링 모듈을 실행시킬 때 실행일을 기준으로 fixed_pub_date_start와 fixed_pub_date_end를  설정하여 중복되지 않는 데이터만 크롤링 할 수 있도록 한다.

page_crawler.py
```
def __get_book_info_from_page(self, c3, start_cnt, show_cnt, fixed_pub_date_start, fixed_pub_date_end) :

   ...

    if temp_book_info['pub_date'] < fixed_pub_date_start or \
        temp_book_info['pub_date'] > fixed_pub_date_end  : #기준일 사이의 출판일을 갖는 도서는 필터링
        raise ValueError()

   ...

```

### 실행 스케줄링은 웹 서버에서 처리

**Comment by kevin0309** [comment]
### 책 제목 중 일부 제목(ex: '.', '사용안함')을 필터링
- __book_name_blacklist 배열에 제외할 책 제목 저장
- 출판일 필터 부분과 책 제목 필터부분을 합쳐서 필터링을 담당하는 메서드로 따로 뺴냄  
  
page_crawler.py
```
    def __validate_book_info(self, book) : 
        #기준일 사이의 출판일을 갖는 도서는 필터링
        if book['pub_date'] < self.start_date or book['pub_date'] > self.end_date  :
            return False

        #책 제목으로 필터링
        for name in PageCrawler.__book_name_blacklist : 
            if book['name'] == name :
                return False

        return True
```
