### ISSUE TITLE
[DB] sysdate()가 실제 시간보다 9시간 이른 시간으로 나오는점 해결하기

### ISSUE THREAD

**Issue by kevin0309** [kevin0309/Cowork_Project_2021#27]
- 시스템 시간을 한국 시간으로 조정하면 될것 같음
- 실사용 DB에 도서 정보 크롤링 하기 전에는 꼭 해결할것!

**Comment by suehyun** [comment]
### AWS RDS mysql 시간 설정(timezone 변경)
* test_group 파라미터 그룹 생성
* **[파라미터 편집]** 에서 time_zone을 Asia/Seoul로 변경
* RDS의 DB파라미터 그룹을 default에서 test_group으로 변경
* **인스턴스 재부팅(중요)**

참고 사이트: https://brtech.tistory.com/95
